# Generated by Django 6.0.1 on 2026-02-01 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="DevLink Technologies", max_length=200),
                ),
                ("tagline", models.CharField(blank=True, max_length=300)),
                (
                    "description",
                    models.TextField(help_text="Company description and mission"),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "services",
                    models.TextField(
                        help_text="Comma-separated list of services (e.g., Web Development, AI, Mobile Apps)"
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedDeveloper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which developers appear (lower numbers first)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("featured_since", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_in_companies",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Developer",
                "verbose_name_plural": "Featured Developers",
                "ordering": ["display_order", "-featured_since"],
                "unique_together": {("portfolio", "is_active")},
            },
        ),
    ]
