# Generated by Django 6.0.1 on 2026-02-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Display name (e.g., 'Azeem Amjad')",
                max_length=200,
            ),
        ),
    ]
